<template>
  <BilibiliFansRankingTable
    title="7日增加排行榜"
    subtitle="近7日粉丝增长"
    value-label="7日增加"
    value-key="delta"
    api-url="/api/bilibili/fans-trend?period=7&direction=up"
    show-sign
  />
</template>
